In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('data/data.csv')
data

        month    income
0     janvier   6778.60
1     fevrier   4671.26
2        mars   6370.00
3       avril  10700.00
4         mai   6955.00
5        juin   6020.54
6     juillet  14341.00
7        aout   3961.00
8   septembre   7300.00
9     octobre   6400.00
10   novembre   5500.00
11   decembre   7000.00
12  janvier25   8000.00
13  fevrier25   8730.00
14     mars25   7100.00
15    avril25   4436.00

In [3]:
data['charges'] = 1845 - 996.50
data

        month    income  charges
0     janvier   6778.60    848.5
1     fevrier   4671.26    848.5
2        mars   6370.00    848.5
3       avril  10700.00    848.5
4         mai   6955.00    848.5
5        juin   6020.54    848.5
6     juillet  14341.00    848.5
7        aout   3961.00    848.5
8   septembre   7300.00    848.5
9     octobre   6400.00    848.5
10   novembre   5500.00    848.5
11   decembre   7000.00    848.5
12  janvier25   8000.00    848.5
13  fevrier25   8730.00    848.5
14     mars25   7100.00    848.5
15    avril25   4436.00    848.5

In [4]:
data['usable'] = (data['income'] / 2) - data['charges']
data

        month    income  charges   usable
0     janvier   6778.60    848.5  2540.80
1     fevrier   4671.26    848.5  1487.13
2        mars   6370.00    848.5  2336.50
3       avril  10700.00    848.5  4501.50
4         mai   6955.00    848.5  2629.00
5        juin   6020.54    848.5  2161.77
6     juillet  14341.00    848.5  6322.00
7        aout   3961.00    848.5  1132.00
8   septembre   7300.00    848.5  2801.50
9     octobre   6400.00    848.5  2351.50
10   novembre   5500.00    848.5  1901.50
11   decembre   7000.00    848.5  2651.50
12  janvier25   8000.00    848.5  3151.50
13  fevrier25   8730.00    848.5  3516.50
14     mars25   7100.00    848.5  2701.50
15    avril25   4436.00    848.5  1369.50

In [5]:
data['salaire'] = round(data['usable'] * (2/3), 2)
data['epargne'] = round(data['usable'] * (1/3), 2)
data.tail()

        month  income  charges  usable  salaire  epargne
11   decembre  7000.0    848.5  2651.5  1767.67   883.83
12  janvier25  8000.0    848.5  3151.5  2101.00  1050.50
13  fevrier25  8730.0    848.5  3516.5  2344.33  1172.17
14     mars25  7100.0    848.5  2701.5  1801.00   900.50
15    avril25  4436.0    848.5  1369.5   913.00   456.50

In [6]:
# virement de 1000 euros fait le 17/11/24

In [7]:
i = (2079 * (12/11))*2
i

4536.0